### ISSUE TITLE
Display location on a map

### ISSUE THREAD

**Issue by paulchamberland** [paulchamberland/MESTO#2]
A building need to be managable. It's need 4 functionnalities. 

1- Save a building : A empty form need to be feel to save with basic validation of datatype, an required field. 

2- Modified a building : After a load of a building, the data is push to a form who the user can change data according to datatype and required validation.

3- Delete a building : After a load of a building, the object can be delete by a simple button.

 4- A list of all site must be visible. Mandatory field visible.

A Building is compose of a serie of data : 

Unique Id database. Integer

Unique reference alpha numeric 20 long *required

Lattitude VARCHAR(45) *

Longitude VARCHAR(45) *

Name VARCHAR(45) *

Description VARCHAR(255)

Adress VARCHAR(45)

City VARCHAR(45)

Province VARCHAR(45)

Country VARCHAR(45)

Postal Code VARCHAR(45)

BeginDate 

EndDate

UpdatedBy : Which user have managed the object

UpdatedDate: When user have modified the object
- a collection of Telecom Room (will be add in another sprint)

**Comment by JonathanLefebvre** [comment]
A building is a type of Site. Site have been done with specific information and more from the time
